name:                raytracing
version:             0.1.0.0
github:              "githubuser/raytracing"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

dependencies:
- base >= 4.7 && < 5
- lens
- linear
- repa
- JuicyPixels

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-unused-top-binds
  - -O2

executables:
  raytracing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracing
