[package]
name = "raytracing"
version = "0.1.0"
authors = ["Boshen"]
edition = "2018"

[dependencies]
image = "0.23.12"
nalgebra = "0.10.*"
rayon = "1.5.*"
rand = "0.7.*"
tobj = "2.0.3"
num-traits = "0.2.6"
enum_dispatch = "0.3.5"
