[package]
name = "raytracing"
version = "0.1.0"
authors = ["Boshen"]
edition = "2021"

[dependencies]
image = "0.23.14"
nalgebra = "0.29.0"
rayon = "1.5.1"
rand = "0.8.4"
tobj = "3.2.0"
num-traits = "0.2.14"
enum_dispatch = "0.3.7"
