[package]
name = "raytracing"
version = "0.1.0"
authors = ["Boshen"]
edition = "2021"

[dependencies]
image = "0.23.14"
nalgebra = "0.29.0"
rayon = "1.5.1"
rand = "0.8.4"
tobj = "3.2.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
